CREATE DATABASE IF NOT EXISTS excuses_de_dev;
USE excuses_de_dev;

CREATE TABLE IF NOT EXISTS tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS excuses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  http_code INT NOT NULL,
  tag_id INT NOT NULL,
  message TEXT NOT NULL,
  FOREIGN KEY (tag_id) REFERENCES tags(id)
);

-- Insérer les tags uniques
INSERT INTO tags (name) VALUES
('Inexcusable'),
('Novelty Implementations'),
('Edge Cases'),
('Fucking'),
('Syntax Errors'),
('Substance'),
('Predictable Problems'),
('Somebody Else''s Problem'),
('Internet crashed');

-- Insérer les excuses avec les tag_id correspondants
INSERT INTO excuses (http_code, tag_id, message) VALUES
(701, (SELECT id FROM tags WHERE name = 'Inexcusable'), 'Meh'),
(702, (SELECT id FROM tags WHERE name = 'Inexcusable'), 'Emacs'),
(703, (SELECT id FROM tags WHERE name = 'Inexcusable'), 'Explosion'),
(704, (SELECT id FROM tags WHERE name = 'Inexcusable'), 'Goto Fail'),
(705, (SELECT id FROM tags WHERE name = 'Inexcusable'), 'I wrote the code and missed the necessary validation by an oversight (see 795)'),
(706, (SELECT id FROM tags WHERE name = 'Inexcusable'), 'Delete Your Account'),
(707, (SELECT id FROM tags WHERE name = 'Inexcusable'), 'Can''t quit vi'),
(710, (SELECT id FROM tags WHERE name = 'Novelty Implementations'), 'PHP'),
(711, (SELECT id FROM tags WHERE name = 'Novelty Implementations'), 'Convenience Store'),
(712, (SELECT id FROM tags WHERE name = 'Novelty Implementations'), 'NoSQL'),
(718, (SELECT id FROM tags WHERE name = 'Novelty Implementations'), 'I am not a teapot'),
(719, (SELECT id FROM tags WHERE name = 'Novelty Implementations'), 'Haskell'),
(720, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'Unpossible'),
(721, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'Known Unknowns'),
(722, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'Unknown Unknowns'),
(723, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'Tricky'),
(724, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'This line should be unreachable'),
(725, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'It works on my machine'),
(726, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'It''s a feature, not a bug'),
(727, (SELECT id FROM tags WHERE name = 'Edge Cases'), '32 bits is plenty'),
(728, (SELECT id FROM tags WHERE name = 'Edge Cases'), 'It works in my timezone'),
(730, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking npm'),
(731, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking Rubygems'),
(732, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking Unic💩de'),
(733, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking Deadlocks'),
(734, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking Deferreds'),
(736, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking Race Conditions'),
(735, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking IE'),
(737, (SELECT id FROM tags WHERE name = 'Fucking'), 'FuckThreadsing'),
(738, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking Exactly'),
(739, (SELECT id FROM tags WHERE name = 'Fucking'), 'Fucking McAfee'),
(750, (SELECT id FROM tags WHERE name = 'Syntax Errors'), 'Didn''t bother to compile it'),
(753, (SELECT id FROM tags WHERE name = 'Syntax Errors'), 'Syntax Error'),
(754, (SELECT id FROM tags WHERE name = 'Syntax Errors'), 'Too many semi-colons'),
(755, (SELECT id FROM tags WHERE name = 'Syntax Errors'), 'Not enough semi-colons'),
(756, (SELECT id FROM tags WHERE name = 'Syntax Errors'), 'Insufficiently polite'),
(757, (SELECT id FROM tags WHERE name = 'Syntax Errors'), 'Excessively polite'),
(759, (SELECT id FROM tags WHERE name = 'Syntax Errors'), 'Unexpected `T_PAAMAYIM_NEKUDOTAYIM`'),
(761, (SELECT id FROM tags WHERE name = 'Substance'), 'Hungover'),
(762, (SELECT id FROM tags WHERE name = 'Substance'), 'Stoned'),
(763, (SELECT id FROM tags WHERE name = 'Substance'), 'Under-Caffeinated'),
(764, (SELECT id FROM tags WHERE name = 'Substance'), 'Over-Caffeinated'),
(765, (SELECT id FROM tags WHERE name = 'Substance'), 'Railscamp'),
(766, (SELECT id FROM tags WHERE name = 'Substance'), 'Sober'),
(767, (SELECT id FROM tags WHERE name = 'Substance'), 'Drunk'),
(768, (SELECT id FROM tags WHERE name = 'Substance'), 'Accidentally Took Sleeping Pills Instead Of Migraine Pills During Crunch Week'),
(771, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Cached for too long'),
(772, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Not cached long enough'),
(773, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Not cached at all'),
(774, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Why was this cached?'),
(775, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Out of cash'),
(776, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Error on the Exception'),
(777, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Coincidence'),
(778, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Off By One Error'),
(779, (SELECT id FROM tags WHERE name = 'Predictable Problems'), 'Off By Too Many To Count Error'),
(780, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'Project owner not responding'),
(781, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'Operations'),
(782, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'QA'),
(783, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'It was a customer request, honestly'),
(784, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'Management, obviously'),
(785, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'TPS Cover Sheet not attached'),
(786, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'Try it now'),
(787, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'Further Funding Required'),
(788, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'Designer''s final designs weren''t'),
(789, (SELECT id FROM tags WHERE name = 'Somebody Else''s Problem'), 'Not my department'),
(791, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'The Internet shut down due to copyright restrictions'),
(792, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'Climate change driven catastrophic weather event'),
(793, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'Zombie Apocalypse'),
(794, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'Someone let PG near a REPL'),
(795, (SELECT id FROM tags WHERE name = 'Internet crashed'), '#heartbleed (see 705)'),
(796, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'Some DNS fuckery idno'),
(797, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'This is the last page of the Internet. Go back'),
(798, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'I checked the db backups cupboard and the cupboard was bare'),
(799, (SELECT id FROM tags WHERE name = 'Internet crashed'), 'End of the world');